name: Powerpipe Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Powerpipe Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Powerpipe
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          curl -L https://powerpipe.io/install/powerpipe.sh | sh
          mv ./powerpipe $HOME/.local/bin/
          chmod +x $HOME/.local/bin/powerpipe
          powerpipe --version

      - name: Setup Steampipe
        run: |
          curl -L https://steampipe.io/install/steampipe.sh | sh
          mkdir -p $HOME/.local/bin
          mv ~/.steampipe/steampipe $HOME/.local/bin/
          chmod +x $HOME/.local/bin/steampipe
          steampipe --version

      - name: Install AWS Plugin
        run: |
          steampipe plugin install aws
          steampipe plugin list

      - name: Install Powerpipe Dependencies
        run: |
          powerpipe mod install
          powerpipe mod list

      - name: Validate Mod Structure
        run: |
          powerpipe mod validate

      - name: Run Detections with Mock Data
        run: |
          # Run all detections to ensure they work with mock data
          powerpipe detection list | grep -v aws_compliance | grep -v aws_insights | while read -r mod name; do
            echo "Running detection: $name"
            powerpipe detection run "$name" || exit 1
          done

      - name: Run Benchmarks with Mock Data
        run: |
          # Run all benchmarks to ensure they work with mock data
          powerpipe benchmark list | grep aws_security_posture | while read -r mod name type; do
            echo "Running benchmark: $name"
            powerpipe benchmark run "$name" || true # Allow failures for now as we're using mock data
          done

      - name: Run Dashboards
        run: |
          # Verify dashboards can be rendered
          powerpipe dashboard list | grep aws_security_posture | while read -r mod name; do
            echo "Testing dashboard: $name"
            powerpipe dashboard run "$name" --output json > /dev/null || exit 1
          done
