name: Powerpipe Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Powerpipe Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Powerpipe
        run: |
          curl -L https://powerpipe.io/install/powerpipe.sh | sudo sh
          powerpipe --version

      - name: Setup Steampipe
        run: |
          curl -L https://steampipe.io/install/steampipe.sh | sudo sh
          steampipe --version

      - name: Setup AWS Credentials for Mock Data
        run: |
          mkdir -p ~/.aws
          echo "[default]
          aws_access_key_id = mock-access-key
          aws_secret_access_key = mock-secret-key
          region = us-east-1" > ~/.aws/credentials
          echo "[default]
          region = us-east-1" > ~/.aws/config

      - name: Install AWS Plugin
        run: |
          steampipe plugin install aws
          steampipe plugin list
          # Create a mock connection config for AWS
          mkdir -p ~/.steampipe/config
          echo 'connection "aws" {
            plugin = "aws"
            regions = ["us-east-1"]
            profile = "default"
          }' > ~/.steampipe/config/aws.spc

      - name: Install Powerpipe Dependencies
        run: |
          powerpipe mod install
          powerpipe mod list

      - name: Validate Mod Structure
        run: |
          powerpipe mod validate

      - name: Run Detections with Mock Data
        run: |
          # Run all detections to ensure they work with mock data
          powerpipe detection list | grep -v aws_compliance | grep -v aws_insights | while read -r mod name; do
            echo "Running detection: $name"
            powerpipe detection run "$name" --snapshot || true # Allow failures for now as we're using mock data
          done

      - name: Run Benchmarks with Mock Data
        run: |
          # Run all benchmarks to ensure they work with mock data
          powerpipe benchmark list | grep aws_security_posture | while read -r mod name type; do
            echo "Running benchmark: $name"
            powerpipe benchmark run "$name" --snapshot || true # Allow failures for now as we're using mock data
          done

      - name: Run Dashboards
        run: |
          # Verify dashboards can be rendered
          powerpipe dashboard list | grep aws_security_posture | while read -r mod name; do
            echo "Testing dashboard: $name"
            powerpipe dashboard run "$name" --snapshot --output json > /dev/null || true # Allow failures for now as we're using mock data
          done
